<?php

namespace App\Services\Payments\Nmi;

use App\Enums\BookingStatus;
use App\Enums\PaymentIntentStatus;
use App\Enums\PaymentProcessor;
use App\Models\Booking;
use App\Models\Charge;
use App\Models\PaymentIntent;
use App\Models\Refund;
use App\Models\User;
use App\Services\Payments\RefundBreakdown;
use Illuminate\Support\Facades\DB;

/**
 * High-level NMI gateway operations (FR-4.1, FR-4.2, FR-4.4).
 *
 * The flow differs from a Stripe-style intents API: NMI is synchronous.
 * Collect.js tokenizes the card in the browser and hands us a one-time
 * payment_token; we POST type=sale to the Payment API and get the verdict
 * in the same round-trip. The PaymentIntent row is therefore OUR local
 * order record (external_intent_id is generated by us and doubles as the
 * NMI orderid), not a gateway-created object. Webhooks reconcile, they
 * don't confirm.
 *
 * NMI has no idempotency-key header, so double-charge protection is done
 * here: chargeIntent() takes a row lock on the intent and no-ops if a
 * successful charge already exists.
 */
class NmiService
{
    public function __construct(private readonly NmiClient $nmi)
    {
    }

    /**
     * Create (or return) the local payment-intent row for a booking. This is
     * purely local — nothing is sent to NMI until the traveler submits a
     * payment_token. external_intent_id doubles as NMI's orderid so gateway
     * reporting and webhooks can be traced back to the booking.
     */
    public function createPaymentIntent(Booking $booking): PaymentIntent
    {
        return PaymentIntent::firstOrCreate(
            [
                'processor' => PaymentProcessor::Nmi->value,
                'external_intent_id' => "booking:{$booking->confirmation_code}",
            ],
            [
                'booking_id' => $booking->id,
                'amount_cents' => $booking->total_cents,
                'currency' => 'USD',
                'status' => PaymentIntentStatus::RequiresPaymentMethod->value,
                'metadata' => [
                    'booking_id' => (string) $booking->id,
                    'confirmation_code' => $booking->confirmation_code,
                    'traveler_id' => (string) $booking->traveler_id,
                    'property_id' => (string) $booking->property_id,
                ],
            ],
        );
    }

    /**
     * Charge a Collect.js payment_token against the intent (type=sale).
     *
     * On approval: records the Charge, marks the intent succeeded, and
     * advances the booking pending_payment → confirmed — synchronously,
     * since NMI's verdict arrives in the API response, not a webhook.
     *
     * @throws NmiPaymentDeclinedException on decline/error (intent left
     *         requires_payment_method so the traveler can retry).
     * @throws NmiTransportException on network failure (state untouched).
     */
    public function chargeIntent(PaymentIntent $intent, string $paymentToken): Charge
    {
        // Row lock so a double-submit can't fire two sales for one intent.
        return DB::transaction(function () use ($intent, $paymentToken) {
            $intent = PaymentIntent::whereKey($intent->id)->lockForUpdate()->firstOrFail();

            $existing = Charge::query()
                ->where('payment_intent_id', $intent->id)
                ->where('captured', true)
                ->first();
            if ($existing && $intent->status === PaymentIntentStatus::Succeeded) {
                return $existing; // already paid — no-op on double submit
            }

            $intent->update(['status' => PaymentIntentStatus::Processing->value]);

            $response = $this->nmi->post([
                'type' => 'sale',
                'payment_token' => $paymentToken,
                'amount' => self::dollars($intent->amount_cents),
                'currency' => strtoupper($intent->currency ?: 'USD'),
                'orderid' => $intent->external_intent_id,
                'order_description' => 'Vaytoven booking '.($intent->metadata['confirmation_code'] ?? $intent->external_intent_id),
            ]);

            if ((int) ($response['response'] ?? 0) !== 1) {
                // Declined/errored — return the intent to a retryable state.
                $intent->update(['status' => PaymentIntentStatus::RequiresPaymentMethod->value]);
                throw new NmiPaymentDeclinedException($response);
            }

            $charge = Charge::create([
                'payment_intent_id' => $intent->id,
                'booking_id' => $intent->booking_id,
                'processor' => PaymentProcessor::Nmi->value,
                'external_charge_id' => (string) $response['transactionid'],
                'amount_cents' => $intent->amount_cents,
                'currency' => strtoupper($intent->currency ?: 'USD'),
                'captured' => true,
                'metadata' => [
                    'authcode' => $response['authcode'] ?? null,
                    'avsresponse' => $response['avsresponse'] ?? null,
                    'cvvresponse' => $response['cvvresponse'] ?? null,
                    'response_code' => $response['response_code'] ?? null,
                ],
            ]);

            $intent->update(['status' => PaymentIntentStatus::Succeeded->value]);

            $booking = $intent->booking;
            if ($booking && $booking->status === BookingStatus::PendingPayment) {
                $booking->transitionTo(BookingStatus::Confirmed, actorUserId: null, reason: 'payment_succeeded');
            }

            return $charge;
        });
    }

    /**
     * Issue a refund against a settled charge (type=refund). Amount comes
     * from RefundCalculator. Double-refund protection: if a refund of this
     * exact amount already exists for the charge, return it instead of
     * hitting the gateway again.
     */
    public function refundCharge(Charge $charge, RefundBreakdown $breakdown, ?int $actorUserId = null, ?string $reason = null): Refund
    {
        if ($breakdown->total_cents <= 0) {
            throw new \InvalidArgumentException('Cannot issue a zero-amount refund');
        }

        $existing = Refund::query()
            ->where('charge_id', $charge->id)
            ->where('amount_cents', $breakdown->total_cents)
            ->first();
        if ($existing) {
            return $existing;
        }

        $response = $this->nmi->post([
            'type' => 'refund',
            'transactionid' => $charge->external_charge_id,
            'amount' => self::dollars($breakdown->total_cents),
        ]);

        if ((int) ($response['response'] ?? 0) !== 1) {
            throw new NmiPaymentDeclinedException($response);
        }

        return Refund::create([
            'charge_id' => $charge->id,
            'booking_id' => $charge->booking_id,
            'actor_user_id' => $actorUserId,
            'processor' => PaymentProcessor::Nmi->value,
            'external_refund_id' => (string) $response['transactionid'],
            'amount_cents' => $breakdown->total_cents,
            'reason' => $reason,
        ]);
    }

    /**
     * Store a tokenized payment method in NMI's Customer Vault for later
     * charges (recurring billing, saved cards, mobile checkout). Returns the
     * customer_vault_id to persist against the user.
     */
    public function storeInVault(User $user, string $paymentToken): string
    {
        $response = $this->nmi->post([
            'customer_vault' => 'add_customer',
            'payment_token' => $paymentToken,
            'first_name' => $user->first_name ?? $user->name ?? '',
            'email' => $user->email,
        ]);

        if ((int) ($response['response'] ?? 0) !== 1) {
            throw new NmiPaymentDeclinedException($response);
        }

        return (string) $response['customer_vault_id'];
    }

    /**
     * Charge a previously vaulted payment method (no token needed).
     */
    public function chargeVault(PaymentIntent $intent, string $customerVaultId): Charge
    {
        return DB::transaction(function () use ($intent, $customerVaultId) {
            $intent = PaymentIntent::whereKey($intent->id)->lockForUpdate()->firstOrFail();

            $response = $this->nmi->post([
                'type' => 'sale',
                'customer_vault_id' => $customerVaultId,
                'amount' => self::dollars($intent->amount_cents),
                'currency' => strtoupper($intent->currency ?: 'USD'),
                'orderid' => $intent->external_intent_id,
            ]);

            if ((int) ($response['response'] ?? 0) !== 1) {
                $intent->update(['status' => PaymentIntentStatus::RequiresPaymentMethod->value]);
                throw new NmiPaymentDeclinedException($response);
            }

            $charge = Charge::create([
                'payment_intent_id' => $intent->id,
                'booking_id' => $intent->booking_id,
                'processor' => PaymentProcessor::Nmi->value,
                'external_charge_id' => (string) $response['transactionid'],
                'amount_cents' => $intent->amount_cents,
                'currency' => strtoupper($intent->currency ?: 'USD'),
                'captured' => true,
                'metadata' => ['customer_vault_id' => $customerVaultId],
            ]);

            $intent->update(['status' => PaymentIntentStatus::Succeeded->value]);

            $booking = $intent->booking;
            if ($booking && $booking->status === BookingStatus::PendingPayment) {
                $booking->transitionTo(BookingStatus::Confirmed, actorUserId: null, reason: 'payment_succeeded');
            }

            return $charge;
        });
    }

    /**
     * NMI takes decimal dollar strings, not cents: 3814 → "38.14".
     */
    public static function dollars(int $cents): string
    {
        return number_format($cents / 100, 2, '.', '');
    }
}
