<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Service Usage Confirmation Certificate — {{ $confirmationCode ?: $userName }}</title>
    <style>
        @page { margin: 1.6cm 1.4cm; }
        * { box-sizing: border-box; }
        body {
            font-family: DejaVu Sans, Helvetica, Arial, sans-serif;
            font-size: 10pt;
            color: #1d1f21;
            line-height: 1.45;
        }
        h1 { font-size: 18pt; margin: 0 0 4px; color: #0e0f12; letter-spacing: -0.01em; }
        h2 { font-size: 12pt; margin: 18px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #d1d5db; color: #111827; }
        .lede { color: #4b5563; font-size: 9.5pt; margin: 0 0 18px; }
        .meta { color: #6b7280; font-size: 8.5pt; margin: 4px 0 0; }
        .pill {
            display: inline-block; padding: 1px 8px; border-radius: 999px; font-size: 8pt;
            background: #ede9fe; color: #5b21b6; font-weight: 600;
        }
        .pill.warn { background: #fef3c7; color: #92400e; }
        .pill.danger { background: #fee2e2; color: #991b1b; }
        table { width: 100%; border-collapse: collapse; margin: 4px 0 12px; font-size: 9pt; }
        th { text-align: left; padding: 6px 8px; background: #f3f4f6; color: #374151; font-weight: 600; border-bottom: 1px solid #d1d5db; }
        td { padding: 5px 8px; border-bottom: 1px solid #f1f3f5; vertical-align: top; }
        .empty { color: #9ca3af; font-style: italic; padding: 6px 0; }
        .footer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #d1d5db; font-size: 8pt; color: #6b7280; }
        .brand { color: #c026d3; font-weight: 700; letter-spacing: 0.04em; }
        .summary { background: #fafaf9; border: 1px solid #e7e5e4; padding: 10px 12px; margin: 8px 0 14px; border-radius: 4px; font-size: 9pt; }
        .summary strong { color: #1d1f21; }
        .mono { font-family: DejaVu Sans Mono, Consolas, monospace; font-size: 8.5pt; }
    </style>
</head>
<body>

<div style="display:flex;align-items:flex-start;justify-content:space-between;">
    <div>
        <div class="brand">VAYTOVEN</div>
        <h1>Service Usage Confirmation Certificate</h1>
    </div>
    <div style="text-align:right;">
        <div class="meta">Generated: {{ $generatedAt }}</div>
        @if($confirmationCode)
            <div class="meta">Booking: <span class="mono">{{ $confirmationCode }}</span></div>
        @endif
    </div>
</div>

<p class="lede">
    This document is generated by Vaytoven's automated chargeback evidence system.
    It records the cardholder's authenticated access to the service, their acceptance
    of governing terms, and their substantive engagement with the booking under dispute.
</p>

<div class="summary">
    <strong>Account holder:</strong> {{ $userName }} &middot;
    <strong>Email:</strong> {{ $userEmail }} &middot;
    <strong>Member since:</strong> {{ $userSince }}
</div>

{{-- ============================================================ --}}
<h2>Authentication history ({{ count($logins) }})</h2>
@if(count($logins) > 0)
    <table>
        <thead>
            <tr>
                <th>When</th><th>Event</th><th>Surface</th><th>IP</th>
                <th>Location</th><th>Device</th><th>Flags</th>
            </tr>
        </thead>
        <tbody>
        @foreach($logins as $row)
            <tr>
                <td class="mono">{{ $row['occurred_at'] }}</td>
                <td>{{ $row['auth_event'] }}</td>
                <td>{{ $row['surface'] }}</td>
                <td class="mono">{{ $row['ip_address'] ?? '—' }}</td>
                <td>{{ $row['city'] ? "{$row['city']}, {$row['country']}" : ($row['country'] ?? '—') }}</td>
                <td>{{ trim(($row['os'] ?? '').' / '.($row['browser'] ?? ''), ' /') ?: '—' }}</td>
                <td>
                    @if($row['is_suspicious'])<span class="pill warn">flagged</span>@endif
                    @if($row['is_vpn'])<span class="pill warn">vpn</span>@endif
                    @if($row['is_tor'])<span class="pill danger">tor</span>@endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@else
    <div class="empty">No login records in the requested window.</div>
@endif

{{-- ============================================================ --}}
<h2>Terms acceptances ({{ count($termsAcceptances) }})</h2>
@if(count($termsAcceptances) > 0)
    <table>
        <thead>
            <tr><th>Document</th><th>Version</th><th>SHA-256</th><th>Accepted at</th></tr>
        </thead>
        <tbody>
        @foreach($termsAcceptances as $row)
            <tr>
                <td>{{ $row['kind'] }}</td>
                <td>{{ $row['version_label'] }}</td>
                <td class="mono">{{ substr($row['content_hash'] ?? '', 0, 16) }}…</td>
                <td class="mono">{{ $row['accepted_at'] }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@else
    <div class="empty">No terms acceptances recorded.</div>
@endif

{{-- ============================================================ --}}
{{-- Vaytoven's own billing. This is the transaction a processor asks about
     when a Member Services payment is disputed; the charges table below it
     belongs to the retired booking product and will be empty. --}}
<h2>Member Services orders</h2>
@if(count($member_service_orders ?? []) > 0)
    <table>
        <thead>
            <tr>
                <th>Order</th><th>Package</th><th>Weeks</th><th>Amount</th>
                <th>Status</th><th>Transaction</th><th>Paid</th>
            </tr>
        </thead>
        <tbody>
        @foreach($member_service_orders as $o)
            <tr>
                <td class="mono">{{ $o['reference'] }}</td>
                <td>{{ $o['package'] }}</td>
                <td>{{ $o['weeks'] }} &times; ${{ number_format(($o['price_per_week_cents'] ?? 0) / 100, 2) }}</td>
                <td>${{ number_format(($o['total_cents'] ?? 0) / 100, 2) }} {{ $o['currency'] }}</td>
                <td>{{ $o['status'] }}</td>
                <td class="mono">{{ $o['nmi_transaction_id'] ?? '—' }}</td>
                <td class="mono">{{ $o['paid_at'] ?? '—' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@else
    <div class="empty">No Member Services orders for this account.</div>
@endif

{{-- Fulfilment. A receipt proves a charge; this proves the advertising was
     actually delivered, against a named property, for a stated period. --}}
<h2>Advertising delivered</h2>
@if(count($advertising_periods ?? []) > 0)
    <table>
        <thead>
            <tr><th>Property</th><th>Location</th><th>From</th><th>To</th><th>Activated</th><th>Status</th></tr>
        </thead>
        <tbody>
        @foreach($advertising_periods as $p)
            <tr>
                <td>{{ $p['property_title'] ?? ('#'.$p['property_id']) }}</td>
                <td>{{ $p['property_city'] ?? '—' }}</td>
                <td class="mono">{{ $p['starts_at'] }}</td>
                <td class="mono">{{ $p['ends_at'] }}</td>
                <td class="mono">{{ $p['activated_at'] ?? '—' }}</td>
                <td>{{ $p['status'] }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@else
    <div class="empty">No advertising periods recorded.</div>
@endif

{{-- What the advertisement actually said while it ran. The live listing may
     share nothing with the version the member paid for. --}}
<h2>Advertisement as published</h2>
@if(count($ad_snapshots ?? []) > 0)
    @foreach($ad_snapshots as $snap)
        <table>
            <thead>
                <tr>
                    <th colspan="2">
                        {{ $snap['content']['title'] ?? 'Listing #'.$snap['property_id'] }}
                        — captured {{ $snap['captured_at'] }} ({{ $snap['reason'] }})
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr><td>Location</td><td>{{ trim(($snap['content']['city'] ?? '').' '.($snap['content']['country'] ?? '')) ?: '—' }}</td></tr>
                {{-- Snapshots captured before the column was renamed carry the old
                         key. Both are read so historical evidence keeps rendering. --}}
                    <tr><td>Price</td><td>${{ number_format((($snap['content']['price_cents'] ?? $snap['content']['base_nightly_cents'] ?? 0)) / 100, 2) }}</td></tr>
                <tr><td>Sleeps</td><td>{{ $snap['content']['capacity'] ?? '—' }}</td></tr>
                <tr><td>Status when captured</td><td>{{ $snap['content']['status'] ?? '—' }}</td></tr>
                <tr>
                    <td>Integrity</td>
                    <td class="mono">
                        {{-- The hash recorded at capture. A snapshot that no
                             longer matches its own hash is flagged rather than
                             presented as evidence. --}}
                        {{ substr($snap['content_hash'], 0, 32) }}…
                        {{ ($snap['intact'] ?? false) ? '(verified unaltered)' : '(FAILED INTEGRITY CHECK)' }}
                    </td>
                </tr>
            </tbody>
        </table>
    @endforeach
@else
    <div class="empty">No advertisement snapshots recorded.</div>
@endif

{{-- ============================================================ --}}
<h2>Charges &amp; refunds</h2>
@if(count($charges) > 0)
    <table>
        <thead>
            <tr><th>Charge ID</th><th>Amount</th><th>Currency</th><th>Captured</th><th>When</th></tr>
        </thead>
        <tbody>
        @foreach($charges as $c)
            <tr>
                <td class="mono">{{ $c['external_charge_id'] }}</td>
                <td>${{ number_format(($c['amount_cents'] ?? 0) / 100, 2) }}</td>
                <td>{{ $c['currency'] }}</td>
                <td>{{ $c['captured'] ? 'yes' : 'no' }}</td>
                <td class="mono">{{ $c['created_at'] }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@else
    <div class="empty">No charges in window.</div>
@endif

@if(count($refunds) > 0)
    <table>
        <thead>
            <tr><th>Refund ID</th><th>Amount</th><th>Reason</th><th>When</th></tr>
        </thead>
        <tbody>
        @foreach($refunds as $r)
            <tr>
                <td class="mono">{{ $r['external_refund_id'] }}</td>
                <td>${{ number_format(($r['amount_cents'] ?? 0) / 100, 2) }}</td>
                <td>{{ $r['reason'] ?? '—' }}</td>
                <td class="mono">{{ $r['created_at'] }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif

{{-- ============================================================ --}}
{{-- The service trail.

     The strongest section in the pack, and the one an issuer reads first:
     the consequential steps only — account created, terms accepted, payment
     approved, advertising activated — in order, each with the address, device
     and session it was performed from.

     None of these can be reported by a web browser. Every one is written by
     the server that performed the action, which is what separates this from a
     page-view log and what makes it worth putting in front of a bank. --}}
<h2>Service trail ({{ count($service_trail ?? []) }})</h2>
@if(count($service_trail ?? []) > 0)
    <table>
        <thead>
            <tr>
                <th>When</th><th>Step</th><th>Result</th><th>Subject</th>
                <th>IP address</th><th>Approx. location</th><th>Device</th>
            </tr>
        </thead>
        <tbody>
        @foreach($service_trail as $s)
            <tr>
                <td class="mono">{{ $s['occurred_at'] }}</td>
                <td>{{ $s['activity'] }}</td>
                <td>{{ $s['result'] ?? '—' }}</td>
                <td class="mono">{{ $s['subject'] ?? '—' }}</td>
                <td class="mono">{{ $s['ip_address'] ?? '—' }}</td>
                <td>{{ $s['approx_location'] ?? '—' }}</td>
                <td>{{ trim(($s['device'] ?? '').' '.($s['browser'] ?? '')) ?: '—' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div class="meta">
        Locations are approximate, derived from the IP address at the time of the
        event. They indicate a general area only and are not a street address or a
        statement of where any person physically was.
    </div>
@else
    <div class="empty">No service-trail events recorded for this account in window.</div>
@endif

{{-- ============================================================ --}}
<h2>High-evidence engagement ({{ $consumptionCount }} of {{ $consumptionCount + $passiveCount }} events)</h2>
@if(count($events) > 0)
    <table>
        <thead><tr><th>When</th><th>Event</th><th>Surface</th></tr></thead>
        <tbody>
        @foreach(array_slice($events, 0, 50) as $e)
            <tr>
                <td class="mono">{{ $e['occurred_at'] }}</td>
                <td>{{ $e['event_type'] }}</td>
                <td>{{ $e['surface'] }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @if(count($events) > 50)
        <div class="meta">…and {{ count($events) - 50 }} more events truncated for layout.</div>
    @endif
@else
    <div class="empty">No engagement events recorded in window.</div>
@endif

{{-- ============================================================ --}}
@if(count($contracts) > 0)
    <h2>Signed agreements ({{ count($contracts) }})</h2>
    <table>
        <thead><tr><th>Envelope</th><th>Subject</th><th>Status</th><th>Completed</th></tr></thead>
        <tbody>
        @foreach($contracts as $c)
            <tr>
                <td class="mono">{{ $c['envelope_id'] }}</td>
                <td>{{ $c['subject'] }}</td>
                <td>{{ $c['status'] }}</td>
                <td class="mono">{{ $c['completed_at'] }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif

<div class="footer">
    <p>This document is generated automatically. Each row reflects a database record
    written at the time of the event. The tracking_events table is append-only at the
    database level (UPDATE and DELETE are rejected by trigger), and rows are linked
    by SHA-256 hash chain — tampering with a historical row breaks chain verification.</p>
    <p>Vaytoven Rentals &middot; Generated for chargeback rebuttal &middot; <span class="brand">VYT</span></p>
</div>

</body>
</html>
