<?php

namespace App\Http\Controllers;

use App\Enums\PropertyStatus;
use App\Models\HelpArticle;
use App\Models\Property;
use Illuminate\Http\Response;

/**
 * XML sitemap for the public site.
 *
 * The route list is written out by hand rather than harvested from the
 * router. A sitemap generated by walking every GET route is how /admin,
 * /account and one-time payment links end up advertised to search engines —
 * an allow-list cannot make that mistake, and the cost is remembering to add
 * a line when a public page is added.
 *
 * Dynamic entries cover only what is genuinely public: active properties,
 * published help articles. A paused listing is deliberately absent — it 404s,
 * and a sitemap full of 404s is worse than a smaller sitemap.
 */
class SitemapController extends Controller
{
    /**
     * Static public pages, with how often each is worth recrawling.
     *
     * @var array<string, string>
     */
    private const PAGES = [
        'properties.index'      => 'daily',
        'hosts.show'            => 'weekly',
        'members.show'          => 'weekly',
        'member-services.show'  => 'weekly',
        'destinations.index'    => 'weekly',
        'about'                 => 'monthly',
        'host-resources.index'  => 'monthly',
        'earnings-calculator'   => 'monthly',
        'mobile-app'            => 'monthly',
        'contact.show'          => 'monthly',
        'trip-support.show'     => 'monthly',
        'careers.index'         => 'weekly',
        'press.index'           => 'weekly',
        'help.index'            => 'weekly',
        'legal.tos'             => 'monthly',
        'legal.privacy'         => 'monthly',
        'legal.member-agreement' => 'monthly',
    ];

    public function __invoke(): Response
    {
        $urls = [['loc' => url('/'), 'changefreq' => 'daily', 'priority' => '1.0']];

        foreach (self::PAGES as $name => $frequency) {
            $urls[] = [
                'loc'        => route($name),
                'changefreq' => $frequency,
                'priority'   => '0.7',
            ];
        }

        foreach ($this->properties() as $property) {
            $urls[] = [
                'loc'        => route('properties.show', $property),
                'lastmod'    => $property->updated_at?->toAtomString(),
                'changefreq' => 'weekly',
                'priority'   => '0.6',
            ];
        }

        foreach ($this->helpArticles() as $article) {
            $urls[] = [
                'loc'        => route('help.show', $article->slug),
                'lastmod'    => $article->updated_at?->toAtomString(),
                'changefreq' => 'monthly',
                'priority'   => '0.4',
            ];
        }

        return response($this->render($urls), 200, [
            'Content-Type'  => 'application/xml; charset=UTF-8',
            // Recrawling is not urgent and this walks two tables.
            'Cache-Control' => 'public, max-age=3600',
        ]);
    }

    private function properties()
    {
        return Property::query()
            ->where('status', PropertyStatus::Active->value)
            ->orderBy('id')
            ->get(['id', 'updated_at']);
    }

    /**
     * Published only. help.show 404s on an unpublished article, so listing
     * one would advertise a dead URL and leak the existence of a draft.
     */
    private function helpArticles()
    {
        return HelpArticle::published()
            ->orderBy('id')
            ->get(['id', 'slug', 'updated_at']);
    }

    /**
     * @param  array<int, array<string, string|null>>  $urls
     */
    private function render(array $urls): string
    {
        $xml = ['<?xml version="1.0" encoding="UTF-8"?>',
                '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'];

        foreach ($urls as $url) {
            $xml[] = '  <url>';
            $xml[] = '    <loc>'.htmlspecialchars($url['loc'], ENT_XML1).'</loc>';

            if (! empty($url['lastmod'])) {
                $xml[] = '    <lastmod>'.$url['lastmod'].'</lastmod>';
            }

            $xml[] = '    <changefreq>'.$url['changefreq'].'</changefreq>';
            $xml[] = '    <priority>'.$url['priority'].'</priority>';
            $xml[] = '  </url>';
        }

        $xml[] = '</urlset>';

        return implode("\n", $xml)."\n";
    }
}
